spring:
  profiles:
    active: dev

cool-code:
  info:
    version: 1.0.0

# 统一异常和统一返回
graceful-response:
  # 自定义Response类的全限定名，默认为空。
  # 配置response-class-full-name后，response-style将不再生效
  # response-class-full-name:
  # Response风格，不配置默认为0
  response-style: 1
  # 自定义的成功响应码，不配置则为0
  default-success-code: 0
  # 自定义的成功提示，默认为ok
  default-success-msg: ok
  # 自定义的失败响应码，默认为1
  default-error-code: -1
  # 自定义的失败提示，默认为error
  default-error-msg: server error!
  # 全局的参数校验错误码，默认等于default-error-code
  default-validate-error-code:
